#!/bin/sh
# scripts/deps-proof.sh — regenerate deps-proof.txt.
#
# Writes the evidence that kap links and vendors nothing outside the C++
# standard library, libc, and POSIX. Committed output is only as good as the
# command that produced it, so this script *is* the claim: run it yourself and
# compare.
#
#     sh scripts/deps-proof.sh
#     make deps-proof            # same thing, writes deps-proof.txt
#
# Every check below either prints evidence or prints why it could not.

set -eu

repo="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo"

binary="${1:-build/kap}"

rule() { printf '\n== %s %s\n\n' "$1" "$(printf '=%.0s' $(seq 1 $((60 - ${#1}))))"; }

printf 'kap - zero-dependency proof\n'
printf 'generated by scripts/deps-proof.sh on %s\n' "$(date -u '+%Y-%m-%d %H:%M:%S UTC')"
printf 'host: %s\n' "$(uname -srm)"

rule "1. what the binary links against"
if [ -x "$binary" ]; then
    if command -v ldd >/dev/null 2>&1; then
        ldd "$binary"
    elif command -v otool >/dev/null 2>&1; then
        otool -L "$binary"
    else
        echo "(neither ldd nor otool available on this host)"
    fi
else
    echo "(no binary at $binary - run 'make' first)"
fi
printf '\nExpected: libstdc++, libgcc_s, libc, libm, the dynamic loader, and\n'
printf 'linux-vdso. Nothing else. Those are the C++ standard library and libc,\n'
printf 'which the rules permit for C/C++.\n'

rule "2. no vendored third-party source"
printf 'Directories named vendor/, third_party/, external/, deps/, extern/:\n'
found=$(find . -type d \( -name vendor -o -name third_party -o -name external \
        -o -name deps -o -name extern \) -not -path './build*' -not -path './.git/*' 2>/dev/null || true)
if [ -z "$found" ]; then echo "  none"; else echo "$found" | sed 's/^/  /'; fi

printf '\nGit submodules:\n'
if [ -f .gitmodules ]; then sed 's/^/  /' .gitmodules; else echo "  none (.gitmodules does not exist)"; fi

rule "3. no package manifest declaring dependencies"
printf 'C++ has no universal manifest; the equivalent is what the build system\n'
printf 'is told to find and link. Comments are stripped first, so a line that\n'
printf 'merely *mentions* FetchContent to say there is none does not count:\n\n'
code=$(sed 's/#.*//' CMakeLists.txt)
for call in find_package FetchContent ExternalProject add_subdirectory \
            pkg_check_modules CPMAddPackage; do
    n=$(printf '%s\n' "$code" | grep -c "$call" || true)
    printf '  %-16s %s\n' "$call" "$n"
done

printf '\nEverything the binary is linked against:\n'
printf '%s\n' "$code" | grep 'target_link_libraries' | sed 's/^[[:space:]]*/    /'
printf '\nkap_core is this repository. There is no other entry.\n'

rule "4. no third-party headers included anywhere"
printf 'Every distinct angle-bracket header included by core/ and tests/,\n'
printf 'split into what provides it:\n\n'
all=$(grep -rh '#include <' core/ tests/ 2>/dev/null \
      | sed 's/.*#include <\([^>]*\)>.*/\1/' | sort -u)

printf '  C++ standard library:\n'
printf '%s\n' "$all" | grep -vE '\.h$' | sed 's/^/    /'

printf '\n  POSIX / libc (permitted for C++ by the rules):\n'
printf '%s\n' "$all" | grep -E '\.h$' | sed 's/^/    /'

printf '\nThat is the complete list. A header from any other project would\n'
printf 'appear here, and none does.\n'

rule "5. what is implemented in-tree instead of imported"
printf 'See STDLIB.md for the full table and rationale. Line counts:\n\n'
for f in core/toml.cpp core/json.cpp core/sha256.hpp core/argv.hpp \
         core/kpl.cpp core/kapc.cpp core/exec.cpp core/fs.hpp \
         core/style.hpp core/hash.hpp tests/harness.hpp; do
    [ -f "$f" ] && printf '  %-22s %5s lines\n' "$f" "$(wc -l < "$f")"
done

rule "6. external programs kap runs (disclosed, not linked)"
printf 'kap is a task runner: running your build tool is the product, not a\n'
printf 'hidden dependency. None of these is linked, and each degrades with a\n'
printf 'message rather than a crash. Full disclosure in STDLIB.md.\n\n'
printf '  build tools : whatever a plugin declares (cmake, cargo, npm, go, ...)\n'
printf '  curl OR wget: only for "kap plugin install" over the network\n'
printf '  git         : only for installing a plugin from a git URL\n'
printf '  sh          : only to run a user-configured hook string\n\n'
printf 'kap builds, tests, detects, and dry-runs with none of them installed.\n'

rule "7. the test suites use no framework"
printf 'tests/harness.hpp is %s lines and is the whole harness. No Catch2, no\n' "$(wc -l < tests/harness.hpp)"
printf 'GoogleTest, no doctest.\n\n'
if [ -x "$binary" ] && [ -x "${binary}_tests" ]; then
    "${binary}_tests" 2>&1 | tail -1 | sed 's/^/  /'
else
    echo "  (build first to see the unit-test count)"
fi

printf '\n== end ======================================================\n'
