# cmake/embed_plugins.cmake
#
# Generates a C++ source file holding the registry index and, optionally, the
# first-party plugins themselves.
#
# Run as a script:
#   cmake -DPLUGIN_DIR=<dir> -DREGISTRY_FILE=<file> -DOUTPUT=<file>
#         [-DEMBED_PLUGINS=ON] -P cmake/embed_plugins.cmake
#
# ## Two different things, embedded on different terms
#
# **The registry index is always embedded.** It is about three kilobytes of
# text naming the first-party plugins and where to fetch each one. Without it, a
# binary with no `<prefix>/share/kap/registry/index.toml` beside it cannot
# answer `kap plugin search`, and `kap plugin install cmake-cpp` fails with
# "cannot resolve" — for a plugin kap has always known about. Compiling it in
# costs nothing and removes a whole class of dead end.
#
# **The plugins are embedded only with -DKAP_EMBED_PLUGINS=ON**, which produces
# a single self-contained binary that needs nothing on disk and no network at
# all. That is the right default for a binary someone will copy around, and the
# wrong one for a distribution package, where the plugins should be files a
# maintainer can see and patch.
#
# ## Why generate rather than commit the result
#
# The generated file is a copy of plugins/*/plugin.kpl. A committed copy is a
# second source of truth that drifts the first time someone edits a plugin and
# forgets — and the symptom would be a binary that behaves differently from the
# repository it was built from. Generating at build time makes that impossible.
#
# ## Why raw string literals
#
# A plugin is UTF-8 text full of quotes and backslashes. Escaping it into a
# conventional string literal is a lot of substitution to get exactly right;
# a raw literal needs none. The delimiter is checked against the content below,
# so a plugin that happened to contain the terminator is a hard error at build
# time rather than a mysterious compile failure.

if(NOT DEFINED PLUGIN_DIR OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "embed_plugins.cmake needs -DPLUGIN_DIR and -DOUTPUT")
endif()

set(_delimiter "KAPEMBED")

# Read one file and emit it as a raw string literal, refusing anything that
# would break out of the literal.
function(kap_raw_literal path out_var)
    file(READ "${path}" _contents)
    if(_contents MATCHES "\\)${_delimiter}\"")
        message(FATAL_ERROR
                "${path} contains the raw-string terminator )${_delimiter}\" and cannot be "
                "embedded. Change the delimiter in cmake/embed_plugins.cmake.")
    endif()
    set(${out_var} "R\"${_delimiter}(${_contents})${_delimiter}\"" PARENT_SCOPE)
endfunction()

set(_body "")
set(_names "")

# Every directory under PLUGIN_DIR that actually holds a plugin. Skipped
# entirely unless plugin embedding was asked for.
file(GLOB _entries RELATIVE "${PLUGIN_DIR}" "${PLUGIN_DIR}/*")
list(SORT _entries)

if(NOT EMBED_PLUGINS)
    set(_entries "")
endif()

foreach(_name IN LISTS _entries)
    set(_manifest "${PLUGIN_DIR}/${_name}/plugin.kpl")
    if(NOT EXISTS "${_manifest}")
        continue()
    endif()

    kap_raw_literal("${_manifest}" _manifest_literal)
    string(APPEND _body
           "        {\"${_name}\",\n"
           "         {{\"plugin.kpl\", ${_manifest_literal}}")

    # README.md is embedded too when present: `kap plugin info` shows it, and a
    # plugin installed from the embedded set should look exactly like one
    # installed from disk.
    set(_readme "${PLUGIN_DIR}/${_name}/README.md")
    if(EXISTS "${_readme}")
        kap_raw_literal("${_readme}" _readme_literal)
        string(APPEND _body ",\n          {\"README.md\", ${_readme_literal}}")
    endif()

    string(APPEND _body "}},\n")
    list(APPEND _names "${_name}")
endforeach()

# The registry index travels with them, so `kap plugin search` works on a
# binary that has never seen a file.
set(_index_literal "\"\"")
if(DEFINED REGISTRY_FILE AND EXISTS "${REGISTRY_FILE}")
    kap_raw_literal("${REGISTRY_FILE}" _index_literal)
endif()

list(JOIN _names " " _name_list)
if(NOT _name_list)
    set(_name_list "(none — the registry index only)")
endif()

if(EMBED_PLUGINS)
    set(_available "true")
else()
    set(_available "false")
endif()

file(WRITE "${OUTPUT}"
"// GENERATED by cmake/embed_plugins.cmake — do not edit.
//
// Source: ${PLUGIN_DIR}
// Plugins: ${_name_list}
//
// This file exists only in a -DKAP_EMBED_PLUGINS=ON build. See core/bundled.hpp.

#include \"core/bundled.hpp\"

namespace kap
{
namespace bundled
{

bool available()
{
    return ${_available};
}

const std::vector<Plugin>& plugins()
{
    static const std::vector<Plugin> all = {
${_body}    };
    return all;
}

std::string_view registry_index()
{
    return ${_index_literal};
}

} // namespace bundled
} // namespace kap
")
